version: '3.3'

services:
  atlas:
    container_name: atlas
    build:
      context: ./atlas
      dockerfile: Dockerfile-dev
    env_file:
      - ./docker/.env.dist
  redis:
    environment: 
      REDIS_PASSWORD: core
  core_database:
    environment:
      MONGODB_DATABASE: core_atlas
      MONGODB_PASSWORD: core
      MONGODB_USERNAME: core